## Project 1: Basic ETL with Pandas
Author: Shravan Jaiswal <br>
The ETL pipeline is complete. It reads data from CSV, Excel, JSON, and Parquet files, cleans it by handling missing values and duplicates, and loads the final dataset to MySQL

- titanic dataset is inbuilt in seaborn library, we can load it directly without downloading.

In [ ]:
import seaborn as sns
titanic = sns.load_dataset('titanic')
titanic

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

- converting dataset to csv, excel, json, parquet formats for testing the ETL pipeline

In [ ]:

titanic.to_csv('titanic.csv', index=False)
titanic.to_excel('titanic.xlsx', index=False)
titanic.to_json('titanic.json', orient='records')
titanic.to_parquet('titanic.parquet', index=False)

- the pipeline reads the file's extension and decides the file type based on which it is labelled.
- next the pipeline cleans the data by handling missing values i.e using median for age and then using astype to assign right categories to the columns
- next the pipeline loads this to MySQL by connecting it to SQL host

In [28]:
import pandas as pd
from sqlalchemy import create_engine
import os

def read_file(file_path):
    ext = os.path.splitext(file_path)[1].lower()
    
    if ext == '.csv':
        return pd.read_csv(file_path)
    elif ext == '.xlsx' or ext == '.xls':
        return pd.read_excel(file_path)
    elif ext == '.json':
        return pd.read_json(file_path, orient='records')
    elif ext == '.parquet':
        return pd.read_parquet(file_path)
    else:
        raise ValueError(f"Unsupported file format: {ext}")

def clean_data(df):
    df.drop_duplicates(inplace=True)
    df.dropna(subset=['embarked'], inplace=True) 

    if 'age' in df.columns:
        df['age'] = df['age'].fillna(df['age'].median())
    if 'sex' in df.columns:
        df['sex'] = df['sex'].astype('category')
    if 'embarked' in df.columns:
        df['embarked'] = df['embarked'].astype('category')    
    return df

def load_to_sql(df, table_name, db_url):
    engine = create_engine(db_url)
    df.to_sql(table_name, con=engine, if_exists='replace', index=False)
    engine.dispose()

def etl_pipeline(file_path, output_table, db_url):
    df = read_file(file_path)
    df_clean = clean_data(df)
    load_to_sql(df_clean, output_table, db_url)
    return df_clean

- here the file input and sql output could be changed to test the Extraction and Loading part of the ETL pipeline with different transformations

In [30]:
db_url = "mysql+pymysql://Shravan:Shravan123@127.0.0.1:3306/sql_inventory"

cleaned_df = etl_pipeline('titanic.csv', 'titanic_clean', db_url)
cleaned_df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
885,0,3,female,39.0,0,5,29.1250,Q,Third,woman,False,NaN,Queenstown,no,False
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,28.0,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

## END OF PROJECT 1